---

- name: Registering the platform domain
  shell: "grep platform_domain /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _platform_domain
- set_fact:
    platform_domain: "{{ _platform_domain.stdout }}"

- name: Registering the front network
  shell: "grep front_network /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _front_network
- set_fact:
    front_network: "{{ _front_network.stdout }}"

- name: Registering the service path
  shell: "grep services_path /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _services_path
- set_fact:
    services_path: "{{ _services_path.stdout }}"

- name: Registering the addons volume
  shell: "grep addons_volume /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _addons_volume
- set_fact:
    addons_volume: "{{ _addons_volume.stdout }}"

# Get the preferred reverse proxy of the platform
- name: Getting the reverse proxy of the platform
  shell: "grep preferred_reverse_proxy /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _preferred_reverse_proxy
- set_fact:
    preferred_reverse_proxy: "{{ _preferred_reverse_proxy.stdout }}"

- name: Registering the nginx container name
  shell: "grep nginx_container_name /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _nginx_container_name
- set_fact:
    nginx_container_name: "{{ _nginx_container_name.stdout }}"

- name: Registering the nginx config volume path
  shell: "grep nginx_config_volume_path /opt/xayma-platform-defaults.yml | cut -d ':' -f2 | awk '{$1=$1};1'"
  register: _nginx_config_volume_path
- set_fact:
    nginx_config_volume_path: "{{ _nginx_config_volume_path.stdout }}"
