---
## Deprecated for now
## Using Traefik
## We will see if we are going to enable it again
- name: Updating the Nginx vHost file
  template:
    src: reverse-proxy.conf.j2
    dest: "{{ nginx_config_volume_path }}/{{ fullinstancename }}.conf"
    mode: '0644'
  notify:
      - reload_nginx_service
  when: instancename != xayma_rapidpro.instancename and ( organization != "" and organization != xayma_rapidpro.organization ) and instancename != domain  
  # We make sure the user has provided an instance name 
  # and he has provided an organization
  # and the new domain name for that instance

  # TODO
  # - [ ] Make sure the nginx service is restarted to take into account new domain name 
  # - [ ] also update the rapidpro internal nginx conf file