---
- name: Starting Rapidpro Service
  docker_compose:
    project_src: "{{ xayma_rapidpro_paths.service }}"
    state: present
  when: instancename != xayma_rapidpro.instancename # We make sure the user has provided an instance name


- name: Updating the nginx vHost file
  template:
    src: reverse-proxy.conf.j2
    dest: "{{ nginx_config_volume_path }}/{{ fullinstancename }}.conf"
    mode: '0644'
  notify:
    - reload_nginx_service
  when: preferred_reverse_proxy == "nginx"