---
## Deprecated for now
## Using Traefik
## We will see if we are going to enable it again
- name: Starting Rapidpro Serice
  docker_compose:
    project_src: "{{ xayma_rapidpro_paths.service }}"
    state: present
  when: instancename != xayma_rapidpro.instancename # We make sure the user has provided an instance name


- name: Updating the Nginx vHost file
  template:
    src: reverse-proxy.conf.j2
    dest: "{{ nginx_config_volume_path }}/{{ fullinstancename }}.conf"
    mode: '0644'
  notify:
      - reload_nginx_service